sections = {}
full_question_names = {
    "Q1": "Q1. I receive training to do my job effectively",
    "Q2": "Q2. There is someone at work who encourages my development",
    "Q3": "Q3. I have been mentored at work",
    "Q4": "Q4. I have received fair consideration for advancement and promotion, when available, within the City of Tempe",
    "Q5": "Q5. I am aware of the City's educational partnerships, Tempe Professional Development Network, The Mentoring Program, and other programs related to professional development and career mobility",
    "Q6": "Q6. The City's programs related to professional development and career mobility, such as educational partnerships, Tempe Professional Development Network, etc., are useful to me",
    "Q7": "Q7. Overall, I am satisfied with the professional development opportunities that are available to me at the City",
    "Q8": "Q8. How could the City improve professional development and/or career mobility for employees?",
    "Q9": "Q9. The following adequately support my work-related needs: The following adequately support my work-related needs:",
    "Q9a": "Q9a. The following adequately support my work-related needs: City Manager's Office",
    "Q9b": "Q9b. The following adequately support my work-related needs: Strategic Management & Diversity Office",
    "Q9c": "Q9c. The following adequately support my work-related needs: Human Resources",
    "Q9d": "Q9d. The following adequately support my work-related needs: Information Technology",
    "Q9e": "Q9e. The following adequately support my work-related needs: Risk Management/Worker's Compensation",
    "Q10": "Q10. The following programs/services adequately support my needs: The following programs/services adequately support my needs:",
    "Q10a": "Q10a. The following programs/services adequately support my needs: The Wellness program",
    "Q10b": "Q10b. The following programs/services adequately support my needs: City mediation services",
    "Q10c": "Q10c. The following programs/services adequately support my needs: The Safe Haven process",
    "Q11": "Q11. Senior leadership in my department is demonstrating and communicating the same values that are expected of me",
    "Q12": "Q12. My physical work environment (building) is safe, clean and maintained in good operating order",
    "Q13": "Q13. Overall, I am satisfied with the support that is provided to employees by the City of Tempe",
    "Q14": "Q14. How could the City improve organizational support for employees?",
    "Q15": "Q15. My immediate supervisor treats me with respect",
    "Q16": "Q16. I know what is expected of me",
    "Q17": "Q17. I have the materials and equipment I need to do my job right",
    "Q18": "Q18. I am comfortable expressing my opinions about work related issues to my immediate supervisor",
    "Q19": "Q19. I believe my opinions seem to count",
    "Q20": "Q20. My work is appreciated by my immediate supervisor",
    "Q21": "Q21. My immediate supervisor gives me clear expectations for work assignments",
    "Q22": "Q22. My immediate supervisor makes good use of my time",
    "Q23": "Q23. I receive constructive feedback on my job performance from my immediate supervisor",
    "Q24": "Q24. The work I perform is evaluated fairly",
    "Q25": "Q25. My immediate supervisor knows my career/job goals",
    "Q26": "Q26. My immediate supervisor supports me in achieving my career/job goals",
    "Q27": "Q27. Within the last 30 days I have received feedback on my job performance from my supervisor",
    "Q28": "Q28. When I request training, my supervisor is open to working with me to ensure I could attend",
    "Q29": "Q29. Senior managers in my department listen to me",
    "Q30": "Q30. I believe senior managers in my department support decisions made by my supervisor",
    "Q31": "Q31. As a supervisor, I am supported when addressing staff issues",
    "Q32": "Q32. Conflict in my work area is resolved effectively",
    "Q33": "Q33. I believe assignments in my department are distributed fairly",
    "Q34": "Q34. I believe exceptional job performance is recognized appropriately by managers/supervisors in my work unit",
    "Q35": "Q35. I believe poor job performance is dealt with effectively by managers/supervisors in my work unit",
    "Q36": "Q36. As a supervisor, I have been given the training, tools, and resources to lead my work unit",
    "Q37": "Q37. I feel safe and comfortable in my work unit",
    "Q38": "Q38. My immediate supervisor has the tools to deal with conflict",
    "Q39": "Q39. Overall, I am satisfied with the working environment in my department",
    "Q41": "Q41. The City's health care plan meets my needs",
    "Q42": "Q42. The amount that I pay for health care benefits is reasonable",
    "Q43": "Q43. The City does a good job of informing me about my benefits",
    "Q44": "Q44. The amount of leave that I receive each year meets my needs",
    "Q45": "Q45. I think the amount I am paid is adequate for the work I do",
    "Q46": "Q46. I am satisfied with the City's deferred compensation benefits",
    "Q47": "Q47. Overall, I am reasonably compensated in pay and benefits for the work I do",
    "Q48": "Q48. How could the City improve compensation and benefits for employees?",
    "Q49": "Q49. I receive information that affects my work in a timely manner from my immediate supervisor",
    "Q50": "Q50. I can express my opinions about work related issues to my department management team",
    "Q51": "Q51. Communication between work units/divisions INSIDE my department is good",
    "Q52": "Q52. Communication between my work unit/division and work units/divisions OUTSIDE my department is good",
    "Q53": "Q53. With respect to my job, communication between departments is good",
    "Q54": "Q54. I have adequate input on decisions affecting my work",
    "Q55": "Q55. Senior managers in my department use input from employees to make decisions",
    "Q56": "Q56. I am encouraged to be innovative and come up with better ways to do things at work",
    "Q57": "Q57. Employees in my department are highly motivated about accomplishing our goals",
    "Q58": "Q58. Overall, I am satisfied with the level of employee engagement in my Department",
    "Q59": "Q59. How could the City improve employee engagement for employees?",
    "Q60": "Q60. My co-workers treat me with respect",
    "Q61": "Q61. Conflict between co-workers is resolved effectively",
    "Q62": "Q62. Overall, I am very satisfied with the quality of peer relationships among City employees",
    "Q63": "Q63. How could the City improve peer relationships among employees?",
    "Q64": "Q64. Are you aware of the Council priorities and the City's Strategic Plan (Planning Process)?",
    "Q65": "Q65. Are you proud to work for the City of Tempe?",
    "Q66": "Q66. Overall, how satisfied are you with your current job?",
    "Q67": "Q67. How has the quality of the work environment in your department changed since you started working for the City of Tempe?",
    "Q68": "Q68. Would you recommend the City of Tempe as a place to work to a friend or relative?",
    "Q69": "Q69. Does the City's working environment and leadership encourage you to go above and beyond the minimum effort that is required for your job?",
    "Q70": "Q70. Would like to finish your career with the City of Tempe?",
    "Q71": "Q71. Have you applied for a new position within the City of Tempe in the past two years?",
}
